build: false

environment:
  matrix:
    - PYTHON_VERSION: "3.7"
      MINICONDA: C:/Miniconda37-x64
init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - ECHO conda --version
  - export CODACY_PROJECT_TOKEN=GdDjegi4fe2u4dnVgx2Z

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-learn pandas joblib pytest
  - activate test-environment
  - conda install -c conda-forge dlib=19.17
  - conda install imageio
  - conda install scikit-image
  - conda install codacy-coverage
  # - conda install -f -y -q --name py37 -c conda-forge --file requirements.txt

test_script:
  - set PYTHONPATH=%PYTHONPATH%;%CD%
  - pytest -sv --ignore=mlearner/plotting
  - python-codacy-coverage -c $APPVEYOR_REPO_COMMIT -d $APPVEYOR_BUILD_FOLDER -r coverage.xml

notifications:

  # Email
  - provider: Webhook
    url: https://webhooks.gitter.im/e/da7cc377188fe3ec803a
    method: GET
    
  - provider: Email
    to:
      - jaisenberafel@gmail.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

