comment: false

codecov:
  notify:
    require_ci_to_pass: no
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        # in the github diff if they install the codecov browser
        # extension:
        # https://github.com/codecov/browser-extension
        target: auto
        threshold: 1%
  notify:
      gitter:
        default:
          url: "https://webhooks.gitter.im/e/8c0d0617855d51cb8d17"
          threshold: 1%


ignore:
- "**/setup.py"