language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
before_install:
  - python --version
  - pip install -r requirements.txt
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest --cov=./ --cov-report=xml # run tests
after_success:
  - codecov # submit coverage
  # - bash <(curl -s https://codecov.io/bash)