name: codacy-analysis-cli

on: ["push"]

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: codacy-analysis-cli
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: mrfyda/codacy-analysis-cli-action@v1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  # codacy-coverage-reporter:
  #   runs-on: ubuntu-latest
  #   name: codacy-coverage-reporter
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run codacy-coverage-reporter
  #       uses: codacy/codacy-coverage-reporter-action@0.1.0
  #       with:
  #         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
